In [9]:
import numpy as np
#assigne input values
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [10]:
#assign output values
output = np.array([0,1,1,0])
output= output.reshape(4,1)
output.shape

(4, 1)

In [11]:
#Assign weights
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [12]:
#add bias
bias = 0.3

In [13]:
#activation function
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [14]:
#derivative of sigmoid function
def der(x):
    return sigmoid_func(x) * (1-sigmoid_func(x))

In [15]:
#updating weiths
for epochs in range(10000):
    input_arr = input_value

    weighted_sum = np.dot(input_arr, weights) + bias
    first_output = sigmoid_func(weighted_sum)

    error = first_output - output
    #mean square error
    total_error = np.square(np.subtract(first_output,output)).mean() 
    #print(total error)

    first_der = error
    second_der = der(first_output)
    derivative = first_der*second_der

    t_input = input_value.T
    final_derivative = np.dot(t_input,derivative)

    #update weight
    weights = weights - 0.05 * final_derivative

    #update bias
    for i in derivative:
        bias = bias - 0.05 * i
    
print(weights)
print(bias)

[[-0.41953547]
 [ 8.98887811]]
[-4.19706344]


In [16]:
#predictions
pred = np.array([0,1])

result = np.dot(pred,weights)+bias

res = sigmoid_func(result)

print(res)

[0.99177089]
